### ISSUE TITLE
sort not working

### ISSUE THREAD

**Issue by hadmut** [osmcode/osmcode.github.io#5]
Hi,
I'm using osmium 1.5.1-1 (ubuntu 17.04), and when trying to sort I get an error message:

% osmosis sort -o Berlin_sort.pbf Berlin.pbf
Jun 07, 2017 1:10:30 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Expected argument 1 to be an option or task name.
	at org.openstreetmap.osmosis.core.cli.CommandLineParser.parse(CommandLineParser.java:79)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:74)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

**Comment by joto** [comment]
a) You are calling `osmosis`, not `osmium`. That is not the same.
b) You are asking this in the wrong place. Either use https://github.com/osmcode/osmium-tool/issues for `osmium-tool` or whereever osmosis wants its reports.

**Comment by hadmut** [comment]
Oh... that's so embarrassing. 

Shell history gave me osmosis instead of osmium and I didn't realize it... sorry.
